### ISSUE TITLE
Uso de Calendar como timestamp

### ISSUE THREAD

**Issue by mauriciobuffon** [trcosta97/api-cliente-produto#4]
Substitua o uso das classes `java.util.Calendar` por `java.time.LocalDateTime` nas suas entidades.

**Comment by trcosta97** [comment]
valeu pelos comentários, é um projeto de estudo, tá ajudando bastante!

**Comment by mauriciobuffon** [comment]
Sim, vi sua pergunta no StackOverflow. Subi um pull-request com algumas modificações que lhe ajudarão com o problema que você relatou lá - ao menos, lhe darão um caminho.
